### ISSUE TITLE
MissingMethodException for addEmbeddableBadgeConfiguration()

### ISSUE THREAD

**Issue by levinanton** [jenkinsci/embeddable-build-status-plugin#55]
I have a Jenkins of ver. 2.190.1 with "Embeddable Build Status" plug-in of ver. 2.0.2 installed.

When trying to invoke a `addEmbeddableBadgeConfiguration()` function from the pipeline script:

`def myCustomBadge = addEmbeddableBadgeConfiguration(id: "myCustomBadge") `

it fails to evaluate the groovy script. Full stack trace:

```
ERROR: Failed to evaluate groovy script.
groovy.lang.MissingMethodException: No signature of method: Script1.addEmbeddableBadgeConfiguration() is applicable for argument types: (java.util.LinkedHashMap) values: [[id:myCustomBadge]]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
	at groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:160)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:157)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:142)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:158)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:162)
	at org.kohsuke.groovy.sandbox.impl.Checker$checkedCall.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
	at Script1.run(Script1.groovy:1)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runScript(GroovySandbox.java:162)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript.evaluate(SecureGroovyScript.java:368)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript.evaluate(SecureGroovyScript.java:312)
	at org.jvnet.hudson.plugins.groovypostbuild.GroovyPostbuildRecorder.perform(GroovyPostbuildRecorder.java:406)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1840)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

Do you have any hints on what might be wrong with my setup?

----

One more observation from "Pipeline Syntax" helper. Snippet generation fails with:

`no public field ‘id’ (or getter method) found in class org.jenkinsci.plugins.badge.dsl.AddEmbeddableBadgeConfigStep`

![2020-02-19_13-15-29](https://user-images.githubusercontent.com/12249110/74833594-12ed0600-531a-11ea-8d31-f5f9d325f3fd.png)

**Comment by MadHawkx** [comment]
Hi.

Has there been any updates on this particular issue? 

@thomas-dee @kohsuke @levinanton @oleg-nenashev

**Comment by MadHawkx** [comment]
Hi.

Any update on this particular issue?

Thanks

@thomas-dee @kohsuke @levinanton @oleg-nenashev

**Comment by oleg-nenashev** [comment]
Currently I do not maintain this plugin. I suggest you use community.jenkins.io for Q&A

**Comment by MadHawkx** [comment]
> Sorry for the lack of response.
> 
> Currently I'm not able to reproduce this but I'll see into it.

Hey @thomas-dee , no issues. Just an update, the issue is not reproducible at my end as well. No idea if @levinanton is still facing it.

**Comment by levinanton** [comment]
Hi @thomas-dee and @MadHawkx 

```
def myCustomBadge = addEmbeddableBadgeConfiguration(id: "myCustomBadge")
```

syntax works now with Jenkins of ver. 2.303.2 and "Embeddable Build Status" plug-in of ver. 2.0.3.

A problem with "Pipeline Syntax" helper (see screenshot in description) is still reproducible but considered as minor thing. We may close this issue. Thanks.
